/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData comment__1_ = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData eye_1 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData twitter_logo = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData twitter_1 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData award = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData remove = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData tick = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData user_1 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData document = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData positive_vote = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData positive_vote_1 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData positive_vote__1_ = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData speed = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData gift_1 = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData curve_arrow = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData like = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData heart__1_ = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData popular__1_ = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData user__1_ = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData magnifier__1_ = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData home__1_ = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData teukoo = const IconData(0xe81d, fontFamily: _kFontFam);
}
